---
title: "This is a test site"
description: |
  Welcome to this website. I hope you enjoy it!
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

# Learn more about publishing to GitHub Pages at:
# https://rstudio.github.io/distill/publish_website.html#github-pages

```

Finally this seems to work.

---

Get the sourcode of this page here: <https://github.com/joundso/joundso.github.io>

---

```{r, layout="l-screen-inset shaded"}
library(leaflet)
leaflet() %>%
  addTiles() %>%  # Add default OpenStreetMap map tiles
  addMarkers(lng=174.768, lat=-36.852, popup="The birthplace of R")
```

```{r, layout="l-body-outset"}
library(rmarkdown)
paged_table(mtcars)
```

```{r diamonds, fig.cap="Diamond Prices"}
library(ggplot2)
ggplot(diamonds, aes(carat, price)) + geom_smooth() +
  facet_grid(~ cut)
```

```{r plots, fig.cap="Test plot"}
p <-   
 ggplot(mpg, aes(displ, hwy)) +
  geom_point() +
  geom_smooth()
plotly::ggplotly(p)
```

